# Project Information
site_name: MacKay Software
site_author: Tim MacKay
site_description: Tim MacKay's personal website
site_url: https://mackaysoftware.com

# Copyright
copyright: Copyright &copy; 2024 Tim MacKay

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Additional dirs to auto-load changes
watch:
  - includes

# Configuration
theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/book
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: light mode
        icon: material/lightbulb
      primary: deep orange
      accent: deep orange
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        name: dark mode
        icon: material/lightbulb-outline
      primary: deep orange
      accent: deep orange
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.indexes
    # enable XHR loading
    - navigation.instant
    - navigation.instant.progress
    # add button to jump to top of page
    - navigation.top
    # update URL with anchors as user scrolls
    - navigation.tracking
    # scroll the sidebar table of contents as the user scrolls
    - toc.follow
    # enhance search
    - search.suggest
    - search.highlight

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simplytim42
      name: Tim's Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tim-mackay-dev
      name: Tim's LinkedIn
    - icon: fontawesome/regular/envelope
      link: mailto:cavil.octet.0w@icloud.com
      name: Tim's Email
    - icon: fontawesome/brands/medium
      link: https://medium.com/@tim_mackay
      name: Tim's Medium Page
    - icon: simple/devdotto
      link: https://dev.to/simplytim42
      name: Tim's Dev.to Page
  analytics:
    provider: google
    property: fake-token

# Extensions
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
      title: On this page
  - footnotes
  # enable assorted functionality
  - attr_list
  - md_in_html
  # enable inline icons an emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # enable call-outs
  - admonition
  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.tasklist:
      custom_checkbox: true
  # enable abbreviations in a glossary
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

# Plugins
plugins:
  - search
  - glightbox
  - blog:
      post_excerpt: required
      post_url_date_format: yyyy
      categories_allowed:
        - Artificial Intelligence
        - Contemplations
        - Learning
      # don't show the draft posts when building the site for prod
      # this is the default but I'm being explicit in case it changes in the future
      draft: false

# Site Navigation
nav:
  - Self-Taught Degree: index.md
  - Blog:
    - blog/index.md
  - about.md
not_in_nav: |
  health-check.html