name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: 0.4.16
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: Install Project
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: uv run scripts/enable_analytics.py
      - run: uv sync

      - name: Deploy Project
        run: uv run mkdocs gh-deploy --force